### ISSUE TITLE
Error: Returned error: insufficient funds for gas * price + value, balance: 0, cost: 210500000000000000

### ISSUE THREAD

**Issue by echocharlie125** [ava-labs/avalanche-faucet-legacy#24]
I'm getting this error each time i try to get faucet from a local installation.
Here are the logs and the error:
 INFO  Starting development server...
10% building 2/2 modules 0 active(X) Droplet size:       1000000000
Asset Id:        AVAX
Faucet Address:          X-local18jma8ppw3nhx5r4ap8clazz0dps7rv5u00z96u
(C) Available Balance:  0
(C) Droplet size:        200000000000000000
(C) Address:  0x751A0B96e1042BeE789452ECb20253Fba40dbE85
Updated Asset Id:  2fombhL7aGPwj3KH4bfrmJwW6PVnMobf9Y2fn9GwxiAAJyFDbe
(X) Available Balance:  300000000000000000
(X) Droplet size:        1000000000
(X) Tx Fee: 100000
40% building 33/71 modules 38 active ...er\lib\index.js??vue-loader-options!-------\faucet-site\node_modules\eslint-loader\index.js??ref--13-0!-------\faucet-site\src\views\Index.vueBrowserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
98% after emitting CopyPlugin

 DONE  Compiled successfully in 11089ms                                                                                                                                                                                              14:42:40

  App running at:
  - Local:   http://localhost:8080/
  - Network: http://X.X.X.X:8080/

  Note that the development build is not optimized.
  To create a production build, run npm run build.

(node:8268) UnhandledPromiseRejectionWarning: Error: Returned error: insufficient funds for gas * price + value, balance: 0, cost: 210500000000000000
    at Object.ErrorResponse (D:\Projets\blockchain\PACTE\faucet\faucet-site\node_modules\web3-core-helpers\src\errors.js:29:16)
    at D:\Projets\blockchain\PACTE\faucet\faucet-site\node_modules\web3-core-requestmanager\src\index.js:140:36
    at XMLHttpRequest.request.onreadystatechange (D:\Projets\blockchain\PACTE\faucet\faucet-site\node_modules\web3-providers-http\src\index.js:110:13)
    at XMLHttpRequestEventTarget.dispatchEvent (D:\Projets\blockchain\PACTE\faucet\faucet-site\node_modules\xhr2-cookies\dist\xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (D:\Projets\blockchain\PACTE\faucet\faucet-site\node_modules\xhr2-cookies\dist\xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (D:\Projets\blockchain\PACTE\faucet\faucet-site\node_modules\xhr2-cookies\dist\xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (D:\Projets\blockchain\PACTE\faucet\faucet-site\node_modules\xhr2-cookies\dist\xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:214:15)
    at endReadableNT (_stream_readable.js:1178:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
(node:8268) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8268) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I'm running a local test network with avash and the five_node_stakin.lua script.

**Comment by dpachecorod** [comment]
Do you find the solution?
